---
- name: "Customizing Kali"
  hosts: kali
  tasks:
    - name: debug user's home dir
      debug: var=ansible_env.HOME
  roles:
    - role: "roles/configure-tmux"
      #- role: "roles/customize-terminal"
    - role: "roles/install-tools"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - GitHub.copilot-nightly
            - snyk-security.snyk-vulnerability-scanner

