- name: copy wallpaper
  copy:
    src: rt16.jpg
    dest: /usr/share/backgrounds/kali/rt.jpg
    owner: root
    group: root
  become: true


- name: "Change wallpaper image"
  community.general.xfconf:
    channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorVirtual1/workspace0/last-image"
    value_type: string
    value: ["/usr/share/backgrounds/kali/rt.jpg"]